import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>MY FAVORITE THING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-1 flex-col justify-center items-center font-sans">
        <h1 className="text-center text-7xl font-bold">
          <p>MY FAVORITE FOOD</p>
        </h1>
        <p className="text-center text-3xl m-5">
          10 favorite fruits and vegetables
        </p>
        <div className="flex items-center justify-center flex-wrap">
          <Link href="/second">
          <div  className="m-4 p-10 text-left text-black hover:text-green-700 m-12 border border-solid border-gray-500 hover:border-green-700 cursor-pointer">
            <h2 className='text-2xl font-bold '>Click❤ &rarr;</h2>
            <p>Introduce you to the list of my favorite foods and reasons why</p> 
          </div>
          </Link>
        </div>
      </main>
    </div>
  )
}
